### ISSUE TITLE
Multi-row of chinese text crossing the border-bottom

### ISSUE THREAD

**Issue by amitbha** [aardappel/treesheets#118] opened 2019-03-27 01:59 UTC
**Description**

If the count of rows of chinese text >= 3, then the last row will cross the border-bottom, looks like strike-through text.

![2019-03-27-095307_637x177_scrot](https://user-images.githubusercontent.com/4060625/55044660-2ba35c00-5076-11e9-8775-c00c86b37718.png)

Text for test:
> 二、积而未作罪。即策划、协商、唆使别人杀生以及随喜他人杀生。无论口中言说，还是以眼神、手势等暗示杀生，自己都会同样犯杀罪。只要众人发心共同造业，最终每个人都会得到全部的业，这就是无欺的因果规律。我经常这样想，造罪业时人越少越好，造善业时人越多越好。

**Specifications**

    Version: TreeSheets Mar  7 2019
    OS: ArchLinux

**Comment by aardappel** [comment] 2019-03-27 02:27
Which font is this? I tried with various fonts on Linux and Windows and couldn't reproduce this problem.

Try Options -> Pick Default Font

**Comment by amitbha** [comment] 2019-03-27 12:51
**English font:** Monaco
**Chinese font:** Source Han Sans CN, maybe

![2019-03-27-204624_867x383_scrot](https://user-images.githubusercontent.com/4060625/55076951-9df55a00-50d1-11e9-8bce-296b08763d41.png)

`fc-list :lang=zh`
> /usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Light.otf: 思源黑体 CN,Source Han Sans CN,Source Han Sans CN Light,思源黑体 CN Light:style=Light,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Heavy.otf: 思源黑体 CN,Source Han Sans CN,Source Han Sans CN Heavy,思源黑体 CN Heavy:style=Heavy,Regular
/usr/share/fonts/adobe-source-han-serif/SourceHanSerifCN-Bold.otf: 思源宋体 CN,Source Han Serif CN:style=Bold
/usr/share/fonts/adobe-source-han-sans/SourceHanSansTW-Bold.otf: Source Han Sans TW,思源黑體 TW:style=Bold
/usr/share/fonts/truetype/myfonts/simkai.ttf: 楷体,KaiTi:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,Arrunta
/usr/share/fonts/adobe-source-han-serif/SourceHanSerifCN-ExtraLight.otf: 思源宋体 CN,Source Han Serif CN,Source Han Serif CN ExtraLight,思源宋体 CN ExtraLight:style=ExtraLight,Regular
/usr/share/fonts/wps-fonts/FZXH1K.TTF: 方正细黑一_GBK,FZXiHeiI\-Z08:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansTW-ExtraLight.otf: Source Han Sans TW,思源黑體 TW,思源黑體 TW ExtraLight,Source Han Sans TW ExtraLight:style=ExtraLight,Regular
/usr/share/fonts/TTF/DroidSansFallbackLegacy.ttf: Droid Sans Fallback:style=Regular
/usr/share/fonts/truetype/myfonts/simfang.ttf: 仿宋,FangSong:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,Arrunta
/usr/share/fonts/misc/18x18ko.pcf.gz: Misc Fixed Wide:style=ko
/usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Bold.otf: 思源黑体 CN,Source Han Sans CN:style=Bold
/usr/share/fonts/wps-fonts/FZWBK.TTF: 方正魏碑_GBK,FZWeiBei\-S03:style=Regular
/usr/share/fonts/wps-fonts/FZBWKZ.ttf: 方正北魏楷书繁体,FZBeiWeiKaiShu\-Z15T:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansTW-Light.otf: Source Han Sans TW,思源黑體 TW,思源黑體 TW Light,Source Han Sans TW Light:style=Light,Regular
/usr/share/fonts/misc/18x18ja.pcf.gz: Misc Fixed Wide:style=ja
/usr/share/fonts/adobe-source-han-sans/SourceHanSansTW-Heavy.otf: Source Han Sans TW,思源黑體 TW,思源黑體 TW Heavy,Source Han Sans TW Heavy:style=Heavy,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-ExtraLight.otf: 思源黑体 CN,Source Han Sans CN,Source Han Sans CN ExtraLight,思源黑体 CN ExtraLight:style=ExtraLight,Regular
/usr/share/fonts/wps-fonts/FZBWKS.ttf: 方正北魏楷书简体,FZBeiWeiKaiShu\-S19S:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Medium.otf: 思源黑体 CN,Source Han Sans CN,Source Han Sans CN Medium,思源黑体 CN Medium:style=Medium,Regular
/usr/share/fonts/truetype/myfonts/simhei.ttf: 黑体,SimHei:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,Arrunta
/usr/share/fonts/adobe-source-han-serif/SourceHanSerifCN-Heavy.otf: 思源宋体 CN,Source Han Serif CN,Source Han Serif CN Heavy,思源宋体 CN Heavy:style=Heavy,Regular
/usr/share/fonts/adobe-source-han-serif/SourceHanSerifCN-Light.otf: 思源宋体 CN,Source Han Serif CN,Source Han Serif CN Light,思源宋体 CN Light:style=Light,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansTW-Regular.otf: Source Han Sans TW,思源黑體 TW:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansTW-Normal.otf: Source Han Sans TW,思源黑體 TW,思源黑體 TW Normal,Source Han Sans TW Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-serif/SourceHanSerifCN-SemiBold.otf: 思源宋体 CN,Source Han Serif CN,Source Han Serif CN SemiBold,思源宋体 CN SemiBold:style=SemiBold,Regular
/usr/share/fonts/TTF/DroidSansFallbackFull.ttf: Droid Sans Fallback:style=Regular
/usr/share/fonts/TTF/DroidSansFallback.ttf: Droid Sans Fallback:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Normal.otf: 思源黑体 CN,Source Han Sans CN,Source Han Sans CN Normal,思源黑体 CN Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-serif/SourceHanSerifCN-Regular.otf: 思源宋体 CN,Source Han Serif CN:style=Regular
/usr/share/fonts/wps-fonts/FZKTK.TTF: 方正楷体_GBK,FZKai\-Z03:style=Regular
/usr/share/fonts/adobe-source-han-serif/SourceHanSerifCN-Medium.otf: 思源宋体 CN,Source Han Serif CN,Source Han Serif CN Medium,思源宋体 CN Medium:style=Medium,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Regular.otf: 思源黑体 CN,Source Han Sans CN:style=Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSansTW-Medium.otf: Source Han Sans TW,思源黑體 TW,思源黑體 TW Medium,Source Han Sans TW Medium:style=Medium,Regular
/usr/share/fonts/wps-fonts/FZLSK.TTF: 方正隶书_GBK,FZLiShu\-S01:style=Regular

**Comment by amitbha** [comment] 2019-03-27 17:20
I changed the default font with every chinese font in OS. Some have the problem, and some don't.
The problem has been solved, but not sure if it's a bug. 😌

**Comment by aardappel** [comment] 2019-03-29 15:20
My list for `fc-list :lang=zh` seems to include mostly variants of `Noto Serif CJK` (this is on Ubuntu), no `SourceHanSansCN`.

I would need to get that installed and set as default somehow.

Even then, I make use of the wxWidgets library font handling, and use the font height it reports to me. So likely it would need to be fixed in wxWidgets or in the font data.

**Closed** 2019-06-18 07:55 UTC
