### ISSUE TITLE
Delete key inserts a character instead of deleting the cell

### ISSUE THREAD

**Issue by mwgamera** [aardappel/treesheets#422] opened 2023-05-28 22:26 UTC
When using the default keybindings with precompiled version from CI on linux (either the linux_treesheets_clang++-12.zip or linux_treesheets_g++-10.zip file, without difference), pressing the DEL key inserts the text `` (0x7f DEL) instead of deleting the selected cell (or deleting the character after the cursor when already in insert mode).

The last build where it worked as expected was 4456947105 (Mar 18 2023) and, all other things being equal, the erroneous behaviour manifested in 4612737023 (Apr 4 2023) and is still present in the latest 5099858955.
I notice it doesn't seem to be related to any change in TreeSheets code itself so I suspect it might be a problem with wxWidgets, but I haven't tried to compile it myself and I can't tell if it needs to be fixed on the wxWidgets' or the TreeSheets' side.

**Comment by aardappel** [comment] 2023-05-30 23:20
Yes, the commit on Apr 4 didn't change any code, so it is indeed likely this happened in wxWidgets in the same timeframe.
@t2b3 

What kind of keyboard do you have?

This one looks suspicious: https://github.com/wxWidgets/wxWidgets/commit/2c0f6a2aa0c8d0650d1f856aa279ce7495925c17

Other than that one I see a ton of Unicode related changes, but I would hope that doesn't affect it.

**Comment by aardappel** [comment] 2023-05-31 16:53
I just meant if its a US keyboard or some other language.. it says `pl` does that mean.. Polish?

**Comment by mwgamera** [comment] 2023-05-31 17:16
Yes, it's Polish. But I believe it should be reproducible with US as well.

**Comment by t2b3** [comment] 2023-06-02 08:49
> y code, so it is indeed likely this happened in wxWidgets in the same timeframe.
> @t2b3

With 3.2.2.1-1 I cannot reproduce this issue. As I am not using Ubuntu, I cannot dig deeper into this issue.

**Comment by mwgamera** [comment] 2023-06-02 19:45
The resulting binary doesn't depend on the system's wxWidgets library and I was under the impression CI builds it off the master branch rather than using 3.2.2.1 which is from Feb 13 (older than the first build that manifested the problem).

**Comment by mwgamera** [comment] 2023-06-04 15:14
I managed to compile 215f382596ee1a18268e099eecd86531edcdf1d7 with wxWidgets/wxWidgets@24a96a78d29bf5af3a5e7ec1a5119f57a163f41c and the Delete key worked normally.
But with wxWidgets/wxWidgets@2c0f6a2aa0c8d0650d1f856aa279ce7495925c17 it exhibited the problem described.
So it looks like the suspicious one is indeed what introduced the breakage. This commit is newer than wxWidgets 3.2.2.1.

While that change is supposed to pertain to non-US layouts, I am fairly certain it affects US layout as well, as I wrote before.

**Comment by aardappel** [comment] 2023-06-04 15:26
@mwgamera thanks for tracking that down, commented on the PR that introduced this problem https://github.com/wxWidgets/wxWidgets/pull/23410

Let's see what they think.. and/or can open an issue on that repo.

**Comment by aardappel** [comment] 2023-06-04 15:42
Actually, looking at the code, this may be due to a long-standing incompatibility between how wxWidgets handles menu keys on Win/Mac vs Linux, see this code we have:

https://github.com/aardappel/treesheets/blob/6059e7ec8e9af3b91c1c935d2833f7932014a784/src/document.h#L822-L858

Try adding this to that section of code and see if that fixes the DEL key:

```
                case WXK_DELETE:
                    return Action(dc, A_DELETE);
```

and you'll also have to change the condition above there such that it reads:

```
if (uk == WXK_NONE || (k < ' ' && k) || k == WXK_DELETE) {
```

If it does, then their recent change just extends their existing Linux menu handling bug to the DEL key, which is sad.

**Comment by aardappel** [comment] 2023-06-05 17:10
Ok committed the fix here: https://github.com/aardappel/treesheets/commit/60bc0d02a8de356715b5a54a177aac530859401d

 I guess I will close this for now.. still a mystery why this stuff is needed on Linux though.

**Closed by aardappel** 2023-06-05 17:10 UTC

**Comment by aardappel** [comment] 2023-09-24 21:57
@mwgamera the wxWidgets people say they may have fixed the issue: https://github.com/wxWidgets/wxWidgets/pull/23410
If you have time, you could try undoing the fix and see if it still works.
You'd need to upgrade to a newer wxWidgets though.

**Comment by t2b3** [comment] 2023-09-26 21:03
@aardappel 
I tested it with the current development code (git master HEAD) of wxWidgets
Unfortunately it does not seem to be fixed:
https://github.com/aardappel/treesheets/assets/3286756/5b4c0a30-2814-4c3c-b826-18daac4455c4

**Comment by aardappel** [comment] 2023-09-26 21:42
@t2b3 thanks for checking!

**Comment by mwgamera** [comment] 2023-10-01 12:45
Thanks for verifying it before I could get around to it. Indeed, the old revision 215f382 compiled with recent wxWidgets/wxWidgets@9b9ec141 still exhibits the same buggy behaviour like it did with wxWidgets/wxWidgets@2c0f6a2.
