### ISSUE TITLE
Cannot start Treesheets on Fedora Linux anymore

### ISSUE THREAD

**Issue by zapateo** [aardappel/treesheets#292] opened 2022-11-30 15:22 UTC
## Description

I cannot run Treesheets on Fedora anymore.

## Steps to reproduce

1. Download the latest build of Treesheets from the release page on GitHub (this happens with both `linux_treesheets_g++-10.zip` and `linux_treesheets_clang++-12.zip`)
2. Unzip the archive
3. Run the `treesheets` executable

## Error

Instead of running Treesheets, I get this error:

```
./treesheets: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
```

I have looked for a missing dependency, but I cannot find anything missing from my system.

## System information

* OS: Fedora Linux 36 (Workstation Edition)
* Desktop Environment: Gnome 42.4
* Running on X11
* CPU: Intel® Core™ i5-4590
* GPU: NVIDIA GeForce GT 1030

**Comment by Vaelatern** [comment] 2022-11-30 17:16
What version of libjpeg.so is installed?

**Comment by aardappel** [comment] 2022-11-30 17:29
These binaries are built on CI with whatever latest Ubuntu they have, which apparently produces a `libjpeg.so.8` dependency.. sounds like you may have to build locally if your system is behind or ahead on that.. Linux is just kind of broken in this regard.

**Comment by zapateo** [comment] 2022-12-01 07:42
> What version of libjpeg.so is installed?

```
Name         : libjpeg-turbo
Version      : 2.1.2
Release      : 2.fc36
Architecture : x86_64
Size         : 651 k
Source       : libjpeg-turbo-2.1.2-2.fc36.src.rpm
Repository   : @System
From repo    : fedora
Summary      : A MMX/SSE2/SIMD accelerated library for manipulating JPEG image files
URL          : http://sourceforge.net/projects/libjpeg-turbo
License      : IJG
Description  : The libjpeg-turbo package contains a library of functions for manipulating JPEG
             : images.
```

**Comment by Philippe-devel-github** [comment] 2022-12-03 22:18
devi aver questo :
# ls -l /usr/lib64/libjpeg.so
lrwxrwxrwx. 1 root root 13 20 janv.  2022 /usr/lib64/libjpeg.so -> libjpeg.so.62
# ls -l /usr/lib64/libjpeg.so.62
lrwxrwxrwx. 1 root root 17 20 janv.  2022 /usr/lib64/libjpeg.so.62 -> libjpeg.so.62.3.0
# ls -l /usr/lib64/libjpeg.so.62.3.0
-rwxr-xr-x. 1 root root 541576 20 janv.  2022 /usr/lib64/libjpeg.so.62.3.0

**Comment by Vaelatern** [comment] 2022-12-03 23:28
That would be why `libjpeg.so.8` doesn't exist on your system. You'll want to re-compile locally or have your distribution package treesheets.

**Comment by georgeraraujo** [comment] 2022-12-05 14:57
As per [this Reddit post](https://www.reddit.com/r/Lutris/comments/nrvcc3/comment/h0ni6tw/?utm_source=share&utm_medium=web2x&context=3), he could try to install libjpeg8 from [this Copr repo](https://copr.fedorainfracloud.org/coprs/aflyhorse/libjpeg/):

```shell
sudo dnf copr add aflyhorse/libjpeg
sudo dnf in libjpeg8
```

**Comment by zapateo** [comment] 2022-12-05 16:18
> As per [this Reddit post](https://www.reddit.com/r/Lutris/comments/nrvcc3/comment/h0ni6tw/?utm_source=share&utm_medium=web2x&context=3), he could try to install libjpeg8 from [this Copr repo](https://copr.fedorainfracloud.org/coprs/aflyhorse/libjpeg/):
> 
> ```shell
> sudo dnf copr add aflyhorse/libjpeg
> sudo dnf in libjpeg8
> ```

It works, thanks 🙂

**Comment by jn64** [comment] 2022-12-11 10:36
Duplicate of #198, which you would find if you search issues for "fedora" or "libjpeg" :)

---

Btw, I have created a package on [Copr jn64/treesheets](https://copr.fedorainfracloud.org/coprs/jn64/treesheets/)

I'm using it myself, but I can only test on Fedora 37 x86_64. I would like to get more feedback before making a wider announcement.

As always with unknown packages, please inspect [the spec file](https://pagure.io/treesheets/blob/main/f/treesheets.spec) and the build information on Copr before installing.

```shell
$ sudo dnf copr enable jn64/treesheets
$ sudo dnf install treesheets
```

The package is built with Fedora's libjpeg-turbo, so it doesn't require libjpeg8 from Copr.

**Comment by MiBengtsson** [comment] 2023-01-03 03:25
Can confirm that it worked on Fedora 36 up until this past week. After a 'dnf update' on Dec 30 or Dec 31, treesheets no longer starts (no output to the terminal).

Yes, I need to do a system upgrade to 37.

**Comment by t2b3** [comment] 2023-11-25 13:48
We do not support distribution-specific issues.

**Closed by t2b3** 2023-11-25 13:48 UTC
