### ISSUE TITLE
Bug with image rendering

### ISSUE THREAD

**Issue by StaffanBetner** [aardappel/treesheets#491] opened 2023-08-12 13:25 UTC
When the mouse pointer is over a cell with an image it renders with in 256 colors mode (I think). 

Compare: 
![image](https://github.com/aardappel/treesheets/assets/8129424/fb3b62b1-093f-48d4-8cda-8cb5b609b309)

![image](https://github.com/aardappel/treesheets/assets/8129424/6ff41634-7700-4b08-9ec1-9ce19a1a9f8c)

**Comment by aardappel** [comment] 2023-08-12 15:56
That is not specific to images, it simply applies the same "hover over" rendering to any cell the mouse is over, which is a XOR operation with the RGB values `0x101014` that for most cells just makes it a little darker.

It be hard to not do this just for images, since images can be an arbitrary subpart of a larger whole.

So the only way would be to use a different rendering method for hover over, but wxWidgets doesn't have any good blending modes.

**Comment by t2b3** [comment] 2023-11-25 13:45
Closing since it is not a bug.

**Closed by t2b3** 2023-11-25 13:45 UTC
