### ISSUE TITLE
Does not run on Linux

### ISSUE THREAD

**Issue by RichardJECooke** [aardappel/treesheets#520] opened 2023-09-21 20:37 UTC
I tried downloading both Linux versions from https://github.com/aardappel/treesheets/releases, unzipping them, and double clicking the `treesheets` file. Nothing happened.

How do I run this app please? Could you make a snap or flatpak version perhaps? It doesn't seem to work

**Comment by aardappel** [comment] 2023-09-21 21:23
Try running it from the shell, see if there is any error output?

We don't build snap/flatpak/ or other custom packaging formats.

**Comment by RichardJECooke** [comment] 2023-09-22 07:39
```
~/Downloads/linux_treesheets_clang++-12/TreeSheets-relocatable$ ./treesheets 
./treesheets: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory
```

**Comment by aardappel** [comment] 2023-09-22 15:27
And? Did you try installing that missing library?

**Comment by RichardJECooke** [comment] 2023-09-22 17:53
It doesn't exist.

**Comment by t2b3** [comment] 2023-09-24 15:06
@RichardJECooke Which Linux distribution do you have installed? The precompiled binaries are supported only a specific Ubuntu version, see the README on the GitHub project page.

**Comment by RichardJECooke** [comment] 2023-09-24 16:14
I'm using standard Ubuntu, the latest version. Which looks like what it requires in your readme. 

This is really why snaps, flathub, app images were invented :(  Never mind, I'll find another note app, thanks

**Comment by jn64** [comment] 2023-09-25 21:13
Duplicate of #439 if you're on Ubuntu 23.04

> I'm using standard Ubuntu, the latest version

Say the actual version number when reporting issues.

> Which looks like what it requires in your readme

[GitHub's `ubuntu-latest` runner is Ubuntu 22.04](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). GitHub only supports the 2 latest Ubuntu LTS versions, so there will not be a Ubuntu 23.04 runner.

It might be possible to use a Ubuntu 23.04 container on the Ubuntu 22.04 runner if we want to make a Ubuntu 23.04 build. See [Running jobs in a container - GitHub Docs](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container).

> This is really why snaps, flathub, app images were invented

Feel free to package it in any of those formats, or make a PPA for Ubuntu, or update the ancient Debian package (which would benefit all Debian downstreams incl Ubuntu). There used to be an AppImage but nobody wants to maintain it. Search issues for "appimage" or "flatpak" for prior discussion.

**Comment by RichardJECooke** [comment] 2023-10-02 09:14
I just noticed there IS a flathub version - https://flathub.org/en-GB/apps/com.strlen.TreeSheets.

If you didn't make it, is it malware?  Should I report it?

**Comment by t2b3** [comment] 2023-10-02 11:53
> I just noticed there IS a flathub version - https://flathub.org/en-GB/apps/com.strlen.TreeSheets.
> 
> 
> 
> If you didn't make it, is it malware?  Should I report it?

I made it so this is no malware :-) It is also linked from in this repository README.

**Closed** 2023-10-02 11:55 UTC
